### ISSUE TITLE
Optimization constraint over transaction costs

### ISSUE THREAD

**Issue by leonardoarcari** [leonardoarcari/dcapal#18]
### Summary

Some brokers apply non-negligible transaction fees that can make investing small amounts quite costly. As suggested in [this Reddit comment][1], investors may want to increase their positions only if transaction fees represent less than some percentage limit of the invested amount.

DcaPal should provide a transaction fees aware optimizer that refuses to invest on an asset if fees are greater than a user-defined percentage.

### Design proposal

Brokers implement the most creative fee structures, varying based on number of trades made per year, size of the investment or asset class. Despite that, they all come down to:

- Absolute fee (e.g. €5 per trade)
- Percentage fee with minimum and maximum (e.g. 0.19% min €1.5 max 18€)

DcaPal should allow a user to define their **fee structure** and **maximum fee rate** ($\hat{r_i}$) they are willing to spend. After computing the amount $a_i$ to allocate on asset $i$, the `OPT` should compute the impact of fee $f_i$ on the investment. 

$$ \frac{f_i}{a_i} > \hat{r_i} \Rightarrow \text{Revert the allocation} $$

_Note:_ Budget reduction due to fees is out of scope, i.e. `OPT` should allocate the budget as if no fees are due.

#### UI changes

- Add general fee structure component in `PortfolioStep` with the following options
  - No fees
  - Absolute fees with `InputNumber` for the amount
  - Percentage fees with percentage, min and max amounts
- Add fee structure component under `Advanced` section of `AssetCard` to set asset-specific fee structure
- Add what-if fee impact on unallocated assets because of too high fees:
  - Amount would have invested
  - Fee would have paid
  - Fee impact

##### Mockups

<img width="2118" alt="mockup" src="https://github.com/leonardoarcari/dcapal/assets/811969/24c19d1f-e2ff-4217-ae8d-ab54a7db0616">

[1]: https://www.reddit.com/r/ItaliaPersonalFinance/comments/12l1r4t/comment/jg7immf/

**Comment by corradopetrelli** [comment]
In my opinion, the **No fee** can simply be traced back to the **Absolute fee** with a value equal to zero, isn't it?

**Comment by leonardoarcari** [comment]
> In my opinion, the **No fee** can simply be traced back to the **Absolute fee** with a value equal to zero, isn't it?

Yep totally agree, I'm planning to do exactly that at optimization level. But UI-wise, isn't it more intuitive to show a **No fee** choice that hides the input fields?

**Comment by corradopetrelli** [comment]
> Yep totally agree, I'm planning to do exactly that at optimization level. But UI-wise, isn't it more intuitive to show a No fee choice that hides the input fields?

Yes it's probably better as you say, mostly for people who don't know the application domain well

**Comment by leonardoarcari** [comment]
Fixed in #31
