### ISSUE TITLE
[Bug]: No budget suggestion when "Fractional Shares" option is selected

### ISSUE THREAD

**Issue by leonardoarcari** [leonardoarcari/dcapal#205]
# **🐞 Bug Report**

## **Describe the bug**

Budget suggestion feature seems to break with `Fractional Shares` option selected. It always returns

> You have already reached your target allocation.

This is most likely related to some bad input FE side. Checking browser Console for logs shows the following:

```
Unexpected exception in dcapal-optimizer: Error: missing field `shares`
```

### **Is this a regression?**

No

### **To Reproduce**

1. Import test case portfolio: [dcapal-portfolio-use_all_budget-low.json](https://github.com/leonardoarcari/dcapal/files/13486980/dcapal-portfolio-use_all_budget-low.json)
2. Click **Next** to go to `InvestStep`
3. Select `Use Fractional Shares` option
4. Go back
5. Click **Next** again
6. **⚠️Budget suggestion returns "_You have already reached your target allocation_"**

### **Expected behaviour**

I think it should work roughly as without _Fractional Shares_ 

### **Media prove**

<img width="497" alt="image" src="https://github.com/leonardoarcari/dcapal/assets/811969/8c6bcf0a-a9fd-4119-8189-9304298f96dd">

<img width="528" alt="image" src="https://github.com/leonardoarcari/dcapal/assets/811969/a6e64bff-dbe5-46a4-a10b-04b756caf4df">

### **Your environment**

* OS: Windows 11
* Node version: v18.16.0
* Npm version: v9.5.1
* Browser name and version: Google Chrome v119.0.6045.160

**Comment by mattiapitossi** [comment]
The issue should now be solved:

https://github.com/leonardoarcari/dcapal/assets/62722102/edf7db45-6535-459e-9e9c-8068031ca5ad
