### ISSUE TITLE
[Proposal] Suggest the minimum investment amount for reach the target allocation

### ISSUE THREAD

**Issue by mattiapitossi** [leonardoarcari/dcapal#33]
### Background

Currently, the web application allows users to insert their assets with target allocations and specify the investment amount. The algorithm then calculates the quantity of each asset to buy/sell while maintaining the balanced weight of ETFs. However, there's an enhancement that could improve the user experience by providing information about the minimum investment required to reach the desired target allocation.

### Proposed Functionality

Before users input the investment amount, the application should provide an estimate of the minimum investment required to achieve the specified target allocation.

For instance, consider the following scenario:

ETF1: Quantity 7, Target Allocation 90%, Price 10€
ETF2: Quantity 0, Target Allocation 10%, Price 10€
In this example, the algorithm should calculate and display a message indicating that a minimum investment of at least 30€ is required to achieve the desired target allocation.

### Use case

- The user loads or inputs the composition of their portfolio.
- The algorithm suggests the minimum amount to invest to reach the desired target allocation.
- The user can choose to invest the suggested amount

**Comment by leonardoarcari** [comment]
Great proposal! I think it's fits nicely with DcaPal and it totally makes sense push the app forward with more what-if analysis features that will give users more insights on their portfolios.

It also looks like a nice and simple task to get some confidence on the codebase and Rust/WASM development. Calculations are not that hard and it doesn't involve too many UI components. What do you think?

**Comment by mattiapitossi** [comment]
Yes, definitely @leonardoarcari! As for the frontend part should be a simple change, could be a good start before moving on with #32

**Comment by leonardoarcari** [comment]
Resolved in #141
