### ISSUE TITLE
[Dev experience] Add issues and pull requests templates

### ISSUE THREAD

**Issue by corradopetrelli** [leonardoarcari/dcapal#42]
Something like that:
![image](https://github.com/leonardoarcari/dcapal/assets/36475130/039a1189-7a82-42aa-82de-4de872cf128f)
![image](https://github.com/leonardoarcari/dcapal/assets/36475130/e994dc2f-1355-4ea9-9798-37c37a4fba4f)

References: 
* https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates
* https://www.gitkraken.com/blog/enhancing-pull-request-descriptions-templates

**Comment by leonardoarcari** [comment]
Oh yeah 💯 Have you already come up with some templates we could use? Feel free to open a PR with them!

**Comment by leonardoarcari** [comment]
Resolved in #44

**Comment by leonardoarcari** [comment]
Resolved in #44
