### ISSUE TITLE
[Feature]: Introduce IT translation

### ISSUE THREAD

**Issue by corradopetrelli** [leonardoarcari/dcapal#55]
# **🚀 Feature Request**

* Introduce IT translation

---

## **Describe the solution you'd like**

* Integrate [react-i18next](https://github.com/i18next/react-i18next)
* Build data structure to manage translation
* Introduce Italian translation

---

## **Describe alternatives you've considered**

Nothing

---

### **Additional context**

In my opinion it is necessary to scale the application

**Comment by corradopetrelli** [comment]
@leonardoarcari I am currently working on this functionality because I consider it necessary.

**Comment by leonardoarcari** [comment]
> @leonardoarcari I am currently working on this functionality because I consider it necessary.

Good stuff mate, thanks! I agree it would help spreading the adoption in the Italian community.

QQ: How you handle `<span>` in localized text? E.g. I'd like to make some words in a string italic or with heavier font?

**Comment by corradopetrelli** [comment]
> QQ: How you handle <span> in localized text? E.g. I'd like to make some words in a string italic or with heavier font?

i18n allows to interpolate strings in these situations. I use the component `<Trans>`.

**Comment by leonardoarcari** [comment]
Resolved in #56
